name: Upload Files to Azure Storage

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
          - dev
          - test
          - prod

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  upload-files:
    
# Define the runner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

# Login to Tenant Azure by Service Principal
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

# Run script that uploading files into the Container in the Storage Account selected during configuration
    - name: Run PowerShell script
      shell: pwsh
      run: |
        ./Script/upload.ps1 -configFile ./Config/parameters.json -inputFolder ./FilesToUpload/${{ github.event.inputs.environment }}