name: Terraform Plan Pipeline

on:
  workflow_dispatch:


#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1  

    - name: Terraform Init
      run: terraform init  

    - name: Request Approval
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          if (pullRequest.requested_reviewers.length === 0) {
            core.setFailed('At least one reviewer must approve the pull request.');
            return;
          }

    - name: Terraform Plan
      run: terraform plan -out=tfplan  

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: tfplan
